version: "3"
services:
  api:
    image: node-test
    build: .
    ports:
      - "3030:3030"
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "~/mongo-data:/data/db"
